name: prepare
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  yaml: ^3.1.2
  yaml_edit: ^2.2.1
  path: ^1.8.0
  args: ^2.5.0
  dart_style: ^2.3.6
  analyzer: <6.5.0
  collection: ^1.18.0
  code_builder: ^4.10.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
