name: rxflutterify_binding
description: >
  A library built on top of Flutter that allows all widgets to automatically rebuild when their input streams emit events,
  making state management easier and more efficient.
version: 0.0.2
homepage: https://github.com/haitr/flutter_clone
repository: https://github.com/haitr/flutter_clone/
issue_tracker: https://github.com/haitr/flutter_clone/issues

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
