name: clone
repository: https://github.com/haitr/flutter_clone

packages:
  - clone/**
  - packages/**

command:
  version:
    # Conventional commits specification: https://conventionalcommits.org
    conventionalCommits: true
    # Include workspace package when versioning
    includeScopes: true

scripts:
  analyze:
    description: Run analyzer in all packages.
    run: melos exec -- dart analyze .

  clone:
    description: Clone Flutter.
    steps:
      - dart run flutter_clone/bin/flutter_clone.dart --output=flutter_example/generated --widget=CupertinoButton

  dry_clone:
    description: Dry run clone Flutter.
    steps:
      - dart run flutter_clone/bin/flutter_clone.dart --dry-run --output=flutter_example/generated
