name: clone
repository: https://github.com/haitr/flutter_clone

packages:
  - clone/**
  - packages/**

command:
  version:
    # Conventional commits specification: https://conventionalcommits.org
    conventionalCommits: true
    # Include workspace package when versioning
    includeScopes: true

scripts:
  analyze:
    description: Run analyzer in all packages.
    run: melos exec -- dart analyze .

  prepare:
    description: Prepare all packages for cloning.
    steps:
      - dart run internal_packages/prepare/bin/prepare.dart

  xx:
    steps:
      - dart run project_analyze/bin/project_analyze.dart -i dependencies/flutter
