library rxflutterify;

import 'widgets/_platform_selectable_region_context_menu_io.dart';
import 'widgets/actions.dart';
import 'widgets/adapter.dart';
import 'widgets/animated_cross_fade.dart';
import 'widgets/animated_scroll_view.dart';
import 'widgets/animated_size.dart';
import 'widgets/animated_switcher.dart';
import 'widgets/annotated_region.dart';
import 'widgets/app.dart';
import 'widgets/async.dart';
import 'widgets/autocomplete.dart';
import 'widgets/autofill.dart';
import 'widgets/automatic_keep_alive.dart';
import 'widgets/banner.dart';
import 'widgets/basic.dart';
import 'widgets/binding.dart';
import 'widgets/color_filter.dart';
import 'widgets/container.dart';
import 'widgets/decorated_sliver.dart';
import 'widgets/default_selection_style.dart';
import 'widgets/default_text_editing_shortcuts.dart';
import 'widgets/dismissible.dart';
import 'widgets/display_feature_sub_screen.dart';
import 'widgets/drag_target.dart';
import 'widgets/draggable_scrollable_sheet.dart';
import 'widgets/dual_transition_builder.dart';
import 'widgets/editable_text.dart';
import 'widgets/fade_in_image.dart';
import 'widgets/focus_scope.dart';
import 'widgets/focus_traversal.dart';
import 'widgets/form.dart';
import 'widgets/framework.dart';
import 'widgets/gesture_detector.dart';
import 'widgets/grid_paper.dart';
import 'widgets/heroes.dart';
import 'widgets/icon.dart';
import 'widgets/icon_theme.dart';
import 'widgets/image.dart';
import 'widgets/image_filter.dart';
import 'widgets/image_icon.dart';
import 'widgets/implicit_animations.dart';
import 'widgets/interactive_viewer.dart';
import 'widgets/keyboard_listener.dart';
import 'widgets/layout_builder.dart';
import 'widgets/list_wheel_scroll_view.dart';
import 'widgets/localizations.dart';
import 'widgets/lookup_boundary.dart';
import 'widgets/magnifier.dart';
import 'widgets/media_query.dart';
import 'widgets/modal_barrier.dart';
import 'widgets/navigation_toolbar.dart';
import 'widgets/navigator.dart';
import 'widgets/navigator_pop_handler.dart';
import 'widgets/nested_scroll_view.dart';
import 'widgets/notification_listener.dart';
import 'widgets/orientation_builder.dart';
import 'widgets/overflow_bar.dart';
import 'widgets/overlay.dart';
import 'widgets/overscroll_indicator.dart';
import 'widgets/page_storage.dart';
import 'widgets/page_view.dart';
import 'widgets/performance_overlay.dart';
import 'widgets/placeholder.dart';
import 'widgets/platform_menu_bar.dart';
import 'widgets/platform_view.dart';
import 'widgets/pop_scope.dart';
import 'widgets/preferred_size.dart';
import 'widgets/primary_scroll_controller.dart';
import 'widgets/raw_keyboard_listener.dart';
import 'widgets/reorderable_list.dart';
import 'widgets/restoration.dart';
import 'widgets/router.dart';
import 'widgets/safe_area.dart';
import 'widgets/scroll_configuration.dart';
import 'widgets/scroll_notification_observer.dart';
import 'widgets/scroll_view.dart';
import 'widgets/scrollable.dart';
import 'widgets/scrollbar.dart';
import 'widgets/selectable_region.dart';
import 'widgets/selection_container.dart';
import 'widgets/semantics_debugger.dart';
import 'widgets/shared_app_data.dart';
import 'widgets/shortcuts.dart';
import 'widgets/single_child_scroll_view.dart';
import 'widgets/size_changed_layout_notifier.dart';
import 'widgets/sliver.dart';
import 'widgets/sliver_fill.dart';
import 'widgets/sliver_layout_builder.dart';
import 'widgets/sliver_persistent_header.dart';
import 'widgets/sliver_prototype_extent_list.dart';
import 'widgets/sliver_varied_extent_list.dart';
import 'widgets/snapshot_widget.dart';
import 'widgets/spacer.dart';
import 'widgets/table.dart';
import 'widgets/tap_region.dart';
import 'widgets/text.dart';
import 'widgets/text_selection.dart';
import 'widgets/texture.dart';
import 'widgets/ticker_provider.dart';
import 'widgets/title.dart';
import 'widgets/transitions.dart';
import 'widgets/tween_animation_builder.dart';
import 'widgets/undo_history.dart';
import 'widgets/value_listenable_builder.dart';
import 'widgets/view.dart';
import 'widgets/viewport.dart';
import 'widgets/visibility.dart';
import 'widgets/widget_inspector.dart';
import 'widgets/will_pop_scope.dart';

export 'package:rxdart/rxdart.dart';
export 'wrapper.dart' show ReactableObjectExt, ListenableExt, BindExt, Wrapper, $;

typedef $ErrorWidget = ErrorWidget;
typedef $TickerMode = TickerMode;
typedef $ScrollConfiguration = ScrollConfiguration;
typedef $PreferredSize = PreferredSize;
typedef $RotatedBox = RotatedBox;
typedef $MouseRegion = MouseRegion;
typedef $ClipPath = ClipPath;
typedef $ConstraintsTransformBox = ConstraintsTransformBox;
typedef $UnconstrainedBox = UnconstrainedBox;
typedef $BlockSemantics = BlockSemantics;
typedef $ColoredBox = ColoredBox;
typedef $FractionalTranslation = FractionalTranslation;
typedef $SizedOverflowBox = SizedOverflowBox;
typedef $SizedBox = SizedBox;
typedef $WidgetToRenderBoxAdapter = WidgetToRenderBoxAdapter;
typedef $Align = Align;
typedef $AbsorbPointer = AbsorbPointer;
typedef $ClipRRect = ClipRRect;
typedef $AspectRatio = AspectRatio;
typedef $IndexedStack = IndexedStack;
typedef $Column = Column;
typedef $BackdropFilter = BackdropFilter;
typedef $Transform = Transform;
typedef $FittedBox = FittedBox;
typedef $IgnoreBaseline = IgnoreBaseline;
typedef $CompositedTransformFollower = CompositedTransformFollower;
typedef $ClipOval = ClipOval;
typedef $RichText = RichText;
typedef $IgnorePointer = IgnorePointer;
typedef $ShaderMask = ShaderMask;
typedef $SliverPadding = SliverPadding;
typedef $CompositedTransformTarget = CompositedTransformTarget;
typedef $PositionedDirectional = PositionedDirectional;
typedef $MetaData = MetaData;
typedef $Semantics = Semantics;
typedef $PhysicalModel = PhysicalModel;
typedef $ConstrainedBox = ConstrainedBox;
typedef $Builder = Builder;
typedef $Center = Center;
typedef $Positioned = Positioned;
typedef $Flow = Flow;
typedef $FractionallySizedBox = FractionallySizedBox;
typedef $Stack = Stack;
typedef $StatefulBuilder = StatefulBuilder;
typedef $KeyedSubtree = KeyedSubtree;
typedef $Listener = Listener;
typedef $ClipRect = ClipRect;
typedef $Baseline = Baseline;
typedef $ListBody = ListBody;
typedef $LayoutId = LayoutId;
typedef $CustomMultiChildLayout = CustomMultiChildLayout;
typedef $SliverToBoxAdapter = SliverToBoxAdapter;
typedef $IndexedSemantics = IndexedSemantics;
typedef $LimitedBox = LimitedBox;
typedef $OverflowBox = OverflowBox;
typedef $Directionality = Directionality;
typedef $DefaultAssetBundle = DefaultAssetBundle;
typedef $Flexible = Flexible;
typedef $Flex = Flex;
typedef $IntrinsicWidth = IntrinsicWidth;
typedef $ExcludeSemantics = ExcludeSemantics;
typedef $Wrap = Wrap;
typedef $Opacity = Opacity;
typedef $CustomPaint = CustomPaint;
typedef $PhysicalShape = PhysicalShape;
typedef $Row = Row;
typedef $Expanded = Expanded;
typedef $MergeSemantics = MergeSemantics;
typedef $RepaintBoundary = RepaintBoundary;
typedef $RawImage = RawImage;
typedef $Padding = Padding;
typedef $IntrinsicHeight = IntrinsicHeight;
typedef $Offstage = Offstage;
typedef $CustomSingleChildLayout = CustomSingleChildLayout;
typedef $MediaQuery = MediaQuery;
typedef $TextSelectionGestureDetector = TextSelectionGestureDetector;
typedef $Localizations = Localizations;
typedef $SlideTransition = SlideTransition;
typedef $PositionedTransition = PositionedTransition;
typedef $DefaultTextStyleTransition = DefaultTextStyleTransition;
typedef $RotationTransition = RotationTransition;
typedef $AnimatedBuilder = AnimatedBuilder;
typedef $MatrixTransition = MatrixTransition;
typedef $FadeTransition = FadeTransition;
typedef $AlignTransition = AlignTransition;
typedef $SizeTransition = SizeTransition;
typedef $SliverFadeTransition = SliverFadeTransition;
typedef $DecoratedBoxTransition = DecoratedBoxTransition;
typedef $ScaleTransition = ScaleTransition;
typedef $ListenableBuilder = ListenableBuilder;
typedef $RelativePositionedTransition = RelativePositionedTransition;
typedef $SliverPersistentHeader = SliverPersistentHeader;
typedef $HeroControllerScope = HeroControllerScope;
typedef $Navigator = Navigator;
typedef $RawScrollbar = RawScrollbar;
typedef $RestorationScope = RestorationScope;
typedef $RootRestorationScope = RootRestorationScope;
typedef $UnmanagedRestorationScope = UnmanagedRestorationScope;
typedef $AutomaticKeepAlive = AutomaticKeepAlive;
typedef $FormField = FormField;
typedef $Form = Form;
typedef $RootWidget = RootWidget;
typedef $Actions = Actions;
typedef $FocusableActionDetector = FocusableActionDetector;
typedef $ActionListener = ActionListener;
typedef $AnimatedFractionallySizedBox = AnimatedFractionallySizedBox;
typedef $AnimatedScale = AnimatedScale;
typedef $AnimatedContainer = AnimatedContainer;
typedef $SliverAnimatedOpacity = SliverAnimatedOpacity;
typedef $AnimatedPhysicalModel = AnimatedPhysicalModel;
typedef $AnimatedPositionedDirectional = AnimatedPositionedDirectional;
typedef $AnimatedRotation = AnimatedRotation;
typedef $AnimatedPositioned = AnimatedPositioned;
typedef $AnimatedOpacity = AnimatedOpacity;
typedef $AnimatedDefaultTextStyle = AnimatedDefaultTextStyle;
typedef $AnimatedPadding = AnimatedPadding;
typedef $AnimatedAlign = AnimatedAlign;
typedef $AnimatedSlide = AnimatedSlide;
typedef $FocusTraversalGroup = FocusTraversalGroup;
typedef $FocusTraversalOrder = FocusTraversalOrder;
typedef $ExcludeFocusTraversal = ExcludeFocusTraversal;
typedef $SnapshotWidget = SnapshotWidget;
typedef $EditableText = EditableText;
typedef $PlatformViewLink = PlatformViewLink;
typedef $PlatformViewSurface = PlatformViewSurface;
typedef $AndroidViewSurface = AndroidViewSurface;
typedef $AndroidView = AndroidView;
typedef $HtmlElementView = HtmlElementView;
typedef $AppKitView = AppKitView;
typedef $UiKitView = UiKitView;
typedef $PlatformSelectableRegionContextMenu = PlatformSelectableRegionContextMenu;
typedef $SelectionRegistrarScope = SelectionRegistrarScope;
typedef $SelectionContainer = SelectionContainer;
typedef $Focus = Focus;
typedef $ExcludeFocus = ExcludeFocus;
typedef $FocusScope = FocusScope;
typedef $Shortcuts = Shortcuts;
typedef $CallbackShortcuts = CallbackShortcuts;
typedef $ShortcutRegistrar = ShortcutRegistrar;
typedef $RenderObjectToWidgetAdapter = RenderObjectToWidgetAdapter;
typedef $AnimatedCrossFade = AnimatedCrossFade;
typedef $AnimatedSize = AnimatedSize;
typedef $AnimatedGrid = AnimatedGrid;
typedef $SliverAnimatedGrid = SliverAnimatedGrid;
typedef $SliverAnimatedList = SliverAnimatedList;
typedef $AnimatedList = AnimatedList;
typedef $ListView = ListView;
typedef $CustomScrollView = CustomScrollView;
typedef $GridView = GridView;
typedef $SliverOpacity = SliverOpacity;
typedef $SliverFixedExtentList = SliverFixedExtentList;
typedef $SliverIgnorePointer = SliverIgnorePointer;
typedef $SliverCrossAxisGroup = SliverCrossAxisGroup;
typedef $KeepAlive = KeepAlive;
typedef $SliverList = SliverList;
typedef $SliverGrid = SliverGrid;
typedef $SliverOffstage = SliverOffstage;
typedef $SliverConstrainedCrossAxis = SliverConstrainedCrossAxis;
typedef $SliverCrossAxisExpanded = SliverCrossAxisExpanded;
typedef $SliverMainAxisGroup = SliverMainAxisGroup;
typedef $AnimatedSwitcher = AnimatedSwitcher;
typedef $AnnotatedRegion = AnnotatedRegion;
typedef $WidgetsApp = WidgetsApp;
typedef $Banner = Banner;
typedef $CheckedModeBanner = CheckedModeBanner;
typedef $DefaultTextEditingShortcuts = DefaultTextEditingShortcuts;
typedef $NotificationListener = NotificationListener;
typedef $PerformanceOverlay = PerformanceOverlay;
typedef $Router = Router;
typedef $BackButtonListener = BackButtonListener;
typedef $SemanticsDebugger = SemanticsDebugger;
typedef $SharedAppData = SharedAppData;
typedef $TapRegionSurface = TapRegionSurface;
typedef $TapRegion = TapRegion;
typedef $TextFieldTapRegion = TextFieldTapRegion;
typedef $DefaultTextHeightBehavior = DefaultTextHeightBehavior;
typedef $Text = Text;
typedef $DefaultTextStyle = DefaultTextStyle;
typedef $Title = Title;
typedef $ValueListenableBuilder = ValueListenableBuilder;
typedef $WidgetInspector = WidgetInspector;
typedef $StreamBuilder = StreamBuilder;
typedef $FutureBuilder = FutureBuilder;
typedef $RawAutocomplete = RawAutocomplete;
typedef $AutocompleteHighlightedOption = AutocompleteHighlightedOption;
typedef $Container = Container;
typedef $DecoratedBox = DecoratedBox;
typedef $OverlayPortal = OverlayPortal;
typedef $Overlay = Overlay;
typedef $AutofillGroup = AutofillGroup;
typedef $Visibility = Visibility;
typedef $SliverVisibility = SliverVisibility;
typedef $PlatformMenuBar = PlatformMenuBar;
typedef $View = View;
typedef $ViewCollection = ViewCollection;
typedef $ViewAnchor = ViewAnchor;
typedef $ColorFiltered = ColorFiltered;
typedef $Image = Image;
typedef $LookupBoundary = LookupBoundary;
typedef $Table = Table;
typedef $TableCell = TableCell;
typedef $DecoratedSliver = DecoratedSliver;
typedef $DefaultSelectionStyle = DefaultSelectionStyle;
typedef $Dismissible = Dismissible;
typedef $RawGestureDetector = RawGestureDetector;
typedef $GestureDetector = GestureDetector;
typedef $DisplayFeatureSubScreen = DisplayFeatureSubScreen;
typedef $LongPressDraggable = LongPressDraggable;
typedef $DragTarget = DragTarget;
typedef $Draggable = Draggable;
typedef $DraggableScrollableActuator = DraggableScrollableActuator;
typedef $DraggableScrollableSheet = DraggableScrollableSheet;
typedef $LayoutBuilder = LayoutBuilder;
typedef $DualTransitionBuilder = DualTransitionBuilder;
typedef $RawMagnifier = RawMagnifier;
typedef $ScrollNotificationObserver = ScrollNotificationObserver;
typedef $TwoDimensionalScrollable = TwoDimensionalScrollable;
typedef $Scrollable = Scrollable;
typedef $SizeChangedLayoutNotifier = SizeChangedLayoutNotifier;
typedef $UndoHistory = UndoHistory;
typedef $FadeInImage = FadeInImage;
typedef $PopScope = PopScope;
typedef $WillPopScope = WillPopScope;
typedef $GridPaper = GridPaper;
typedef $HeroMode = HeroMode;
typedef $Hero = Hero;
typedef $Icon = Icon;
typedef $IconTheme = IconTheme;
typedef $Placeholder = Placeholder;
typedef $ImageFiltered = ImageFiltered;
typedef $ImageIcon = ImageIcon;
typedef $InteractiveViewer = InteractiveViewer;
typedef $KeyboardListener = KeyboardListener;
typedef $ListWheelScrollView = ListWheelScrollView;
typedef $ListWheelViewport = ListWheelViewport;
typedef $AnimatedModalBarrier = AnimatedModalBarrier;
typedef $ModalBarrier = ModalBarrier;
typedef $NavigationToolbar = NavigationToolbar;
typedef $NavigatorPopHandler = NavigatorPopHandler;
typedef $NestedScrollViewViewport = NestedScrollViewViewport;
typedef $NestedScrollView = NestedScrollView;
typedef $SliverOverlapAbsorber = SliverOverlapAbsorber;
typedef $SliverOverlapInjector = SliverOverlapInjector;
typedef $PrimaryScrollController = PrimaryScrollController;
typedef $SliverFillRemaining = SliverFillRemaining;
typedef $SliverFillViewport = SliverFillViewport;
typedef $ShrinkWrappingViewport = ShrinkWrappingViewport;
typedef $Viewport = Viewport;
typedef $OrientationBuilder = OrientationBuilder;
typedef $OverflowBar = OverflowBar;
typedef $StretchingOverscrollIndicator = StretchingOverscrollIndicator;
typedef $GlowingOverscrollIndicator = GlowingOverscrollIndicator;
typedef $PageStorage = PageStorage;
typedef $PageView = PageView;
typedef $RawKeyboardListener = RawKeyboardListener;
typedef $ReorderableDelayedDragStartListener = ReorderableDelayedDragStartListener;
typedef $ReorderableList = ReorderableList;
typedef $ReorderableDragStartListener = ReorderableDragStartListener;
typedef $SliverReorderableList = SliverReorderableList;
typedef $SliverPrototypeExtentList = SliverPrototypeExtentList;
typedef $SliverVariedExtentList = SliverVariedExtentList;
typedef $SliverSafeArea = SliverSafeArea;
typedef $SafeArea = SafeArea;
typedef $SelectableRegion = SelectableRegion;
typedef $SingleChildScrollView = SingleChildScrollView;
typedef $SliverLayoutBuilder = SliverLayoutBuilder;
typedef $Spacer = Spacer;
typedef $Texture = Texture;
typedef $TweenAnimationBuilder = TweenAnimationBuilder;
