name: api_search
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxflutterify: ^0.0.1
  cupertino_icons: ^1.0.6

  dio: ^5.1.1
  freezed_annotation: ^2.1.0
  pubspec_parse: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner: ^2.0.0
  freezed: ^2.1.0
  json_serializable: ^6.3.0

dependency_overrides:
  rxflutterify:
    path: ../../

flutter:
  uses-material-design: true
