include: package:lints/recommended.yaml

linter:
  rules:
    camel_case_types: true
    public_member_api_docs: true
    slash_for_doc_comments: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    depend_on_referenced_packages: false

analyzer:
  exclude:
    - "dependencies/**"
