name: clone
description: .
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
  analyzer: <6.7.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

dependencies:
  prepare:
    path: prepare
  path: ^1.8.0
  args: ^2.5.0
  json_annotation: ^4.9.0
  collection: ^1.18.0
  code_builder: ^4.10.0
  archive: ^3.6.1
  cli_util: ^0.4.1
  console_bars: ^1.2.0
  chalkdart: ^2.2.1
  dart_style: ^2.3.6
