name: riverpod_widget
description: >
  A library built on top of Flutter that allows all widgets to automatically rebuild when corresponding providers notified,
  making state management easier and more efficient.
version: 0.0.2
homepage: https://github.com/haitr/flutter_clone
repository: https://github.com/haitr/flutter_clone/tree/main/packages/riverpod_widget
issue_tracker: https://github.com/haitr/flutter_clone/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+riverpod_widget%22
topics:
  - reactive-programming
  - riverpod

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
