name: cart
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxflutter: ^0.0.1
  cupertino_icons: ^1.0.6
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  rxflutter:
    path: ../../

flutter:
  uses-material-design: true
