library rxflutterify; // ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:ui' as ui;

import 'package:flutter/foundation.dart' as _i2;
import 'package:flutter/material.dart' as _i1;
import 'package:flutter/painting.dart' as _i5;
import 'package:flutter/services.dart' as _i3;
import 'package:flutter/widgets.dart' as _i4;

import '../wrapper.dart';

final class RadioListTile<T> extends Wrapper {
  @Goto(_i1.RadioListTile.new)
  RadioListTile(
    $ $config, {
    _i2.Key? key,
    required T value,
    required T? groupValue,
    required _i2.ValueChanged<T?>? onChanged,
    _i3.MouseCursor? mouseCursor,
    bool toggleable = false,
    ui.Color? activeColor,
    _i4.WidgetStateProperty<ui.Color?>? fillColor,
    ui.Color? hoverColor,
    _i4.WidgetStateProperty<ui.Color?>? overlayColor,
    double? splashRadius,
    _i1.MaterialTapTargetSize? materialTapTargetSize,
    _i4.Widget? title,
    _i4.Widget? subtitle,
    bool isThreeLine = false,
    bool? dense,
    _i4.Widget? secondary,
    bool selected = false,
    _i1.ListTileControlAffinity controlAffinity = _i1.ListTileControlAffinity.platform,
    bool autofocus = false,
    _i5.EdgeInsetsGeometry? contentPadding,
    _i5.ShapeBorder? shape,
    ui.Color? tileColor,
    ui.Color? selectedTileColor,
    _i1.VisualDensity? visualDensity,
    _i4.FocusNode? focusNode,
    _i2.ValueChanged<bool>? onFocusChange,
    bool? enableFeedback,
  }) : super(
          Argument({
            #key: key,
            #value: value,
            #groupValue: groupValue,
            #onChanged: onChanged,
            #mouseCursor: mouseCursor,
            #toggleable: toggleable,
            #activeColor: activeColor,
            #fillColor: fillColor,
            #hoverColor: hoverColor,
            #overlayColor: overlayColor,
            #splashRadius: splashRadius,
            #materialTapTargetSize: materialTapTargetSize,
            #title: title,
            #subtitle: subtitle,
            #isThreeLine: isThreeLine,
            #dense: dense,
            #secondary: secondary,
            #selected: selected,
            #controlAffinity: controlAffinity,
            #autofocus: autofocus,
            #contentPadding: contentPadding,
            #shape: shape,
            #tileColor: tileColor,
            #selectedTileColor: selectedTileColor,
            #visualDensity: visualDensity,
            #focusNode: focusNode,
            #onFocusChange: onFocusChange,
            #enableFeedback: enableFeedback,
          }),
          builder: (args) => _i1.RadioListTile<T>(
            key: args(#key),
            value: args(#value),
            groupValue: args(#groupValue),
            onChanged: args(#onChanged),
            mouseCursor: args(#mouseCursor),
            toggleable: args(#toggleable),
            activeColor: args(#activeColor),
            fillColor: args(#fillColor),
            hoverColor: args(#hoverColor),
            overlayColor: args(#overlayColor),
            splashRadius: args(#splashRadius),
            materialTapTargetSize: args(#materialTapTargetSize),
            title: args(#title),
            subtitle: args(#subtitle),
            isThreeLine: args(#isThreeLine),
            dense: args(#dense),
            secondary: args(#secondary),
            selected: args(#selected),
            controlAffinity: args(#controlAffinity),
            autofocus: args(#autofocus),
            contentPadding: args(#contentPadding),
            shape: args(#shape),
            tileColor: args(#tileColor),
            selectedTileColor: args(#selectedTileColor),
            visualDensity: args(#visualDensity),
            focusNode: args(#focusNode),
            onFocusChange: args(#onFocusChange),
            enableFeedback: args(#enableFeedback),
          ),
        );

  @Goto(_i1.RadioListTile.adaptive)
  RadioListTile.adaptive(
    $ $config, {
    _i2.Key? key,
    required T value,
    required T? groupValue,
    required _i2.ValueChanged<T?>? onChanged,
    _i3.MouseCursor? mouseCursor,
    bool toggleable = false,
    ui.Color? activeColor,
    _i4.WidgetStateProperty<ui.Color?>? fillColor,
    ui.Color? hoverColor,
    _i4.WidgetStateProperty<ui.Color?>? overlayColor,
    double? splashRadius,
    _i1.MaterialTapTargetSize? materialTapTargetSize,
    _i4.Widget? title,
    _i4.Widget? subtitle,
    bool isThreeLine = false,
    bool? dense,
    _i4.Widget? secondary,
    bool selected = false,
    _i1.ListTileControlAffinity controlAffinity = _i1.ListTileControlAffinity.platform,
    bool autofocus = false,
    _i5.EdgeInsetsGeometry? contentPadding,
    _i5.ShapeBorder? shape,
    ui.Color? tileColor,
    ui.Color? selectedTileColor,
    _i1.VisualDensity? visualDensity,
    _i4.FocusNode? focusNode,
    _i2.ValueChanged<bool>? onFocusChange,
    bool? enableFeedback,
    bool useCupertinoCheckmarkStyle = false,
  }) : super(
          Argument({
            #key: key,
            #value: value,
            #groupValue: groupValue,
            #onChanged: onChanged,
            #mouseCursor: mouseCursor,
            #toggleable: toggleable,
            #activeColor: activeColor,
            #fillColor: fillColor,
            #hoverColor: hoverColor,
            #overlayColor: overlayColor,
            #splashRadius: splashRadius,
            #materialTapTargetSize: materialTapTargetSize,
            #title: title,
            #subtitle: subtitle,
            #isThreeLine: isThreeLine,
            #dense: dense,
            #secondary: secondary,
            #selected: selected,
            #controlAffinity: controlAffinity,
            #autofocus: autofocus,
            #contentPadding: contentPadding,
            #shape: shape,
            #tileColor: tileColor,
            #selectedTileColor: selectedTileColor,
            #visualDensity: visualDensity,
            #focusNode: focusNode,
            #onFocusChange: onFocusChange,
            #enableFeedback: enableFeedback,
            #useCupertinoCheckmarkStyle: useCupertinoCheckmarkStyle,
          }),
          builder: (args) => _i1.RadioListTile<T>.adaptive(
            key: args(#key),
            value: args(#value),
            groupValue: args(#groupValue),
            onChanged: args(#onChanged),
            mouseCursor: args(#mouseCursor),
            toggleable: args(#toggleable),
            activeColor: args(#activeColor),
            fillColor: args(#fillColor),
            hoverColor: args(#hoverColor),
            overlayColor: args(#overlayColor),
            splashRadius: args(#splashRadius),
            materialTapTargetSize: args(#materialTapTargetSize),
            title: args(#title),
            subtitle: args(#subtitle),
            isThreeLine: args(#isThreeLine),
            dense: args(#dense),
            secondary: args(#secondary),
            selected: args(#selected),
            controlAffinity: args(#controlAffinity),
            autofocus: args(#autofocus),
            contentPadding: args(#contentPadding),
            shape: args(#shape),
            tileColor: args(#tileColor),
            selectedTileColor: args(#selectedTileColor),
            visualDensity: args(#visualDensity),
            focusNode: args(#focusNode),
            onFocusChange: args(#onFocusChange),
            enableFeedback: args(#enableFeedback),
            useCupertinoCheckmarkStyle: args(#useCupertinoCheckmarkStyle),
          ),
        );
}
